# include "ft_map.h"
# include <dirent.h>
# include <stdio.h>

int						main()
{
	t_map				*map;

	map = ft_mapnew(NULL);
	// map = ft_strnew(&hashfunc);

	ft_mapinsert(map, "cdasgd", "/bidsagn");
	ft_mapinsert(map, "cd31asgd", "/bidsagn");
	ft_mapinsert(map, "c31dasgdjj", "/bidsagn");
	ft_mapinsert(map, "cdaf3r2sgd", "/bidsagn");
	ft_mapinsert(map, "3121", "/bidsagn");
	ft_mapinsert(map, "13566", "/bidsagn");
	ft_mapinsert(map, "cd", "/bin");
	ft_mapinsert(map, "cd", "lala");
	ft_mapinsert(map, "pwd", "1");
	ft_mapinsert(map, "pwd", "1");
	ft_mapinsert(map, "pfagawd", "1");
	ft_mapinsert(map, "pwagd", "1");
	ft_mapinsert(map, "asdgasdpwd", "1");
	ft_mapinsert(map, "pagD43Qwd", "1");
	ft_mapinsert(map, "pG3QARWGwd", "1");
	ft_mapinsert(map, "pg3q4Awd", "1");
	ft_mapinsert(map, "pwGQ34d", "1");
	ft_mapinsert(map, "pwGrgd", "1");
	ft_mapinsert(map, "p", "1");
	ft_mapinsert(map, "pgWEGAGwd", "1");
	ft_mapinsert(map, "253pwd", "1");
	ft_mapinsert(map, "25pwd52525", "1");
	ft_mapinsert(map, "p25w5235d", "1");
	ft_mapinsert(map, "pw25SDGADHAHd", "1");
	ft_mapinsert(map, "pw&*^&&d", "1");
	ft_mapinsert(map, "p#%#H3QJwd", "1");
	ft_mapinsert(map, "pwFDHSHDFAd", "1");
	ft_mapinsert(map, "AFHGpwd", "1");
	ft_mapinsert(map, "ASHGFHDApwd", "1");
	ft_mapinsert(map, "pfsadgaGDSGSDGSGGGGSDafhdhdfhgfshGKSHGJJSGJHSHGHSDHHJ SD HJHFG H344H48`&Y^&Y U(99358738U&*#^&wd", "1");
	ft_mapinsert(map, "GDS`KHGSK", "1");
	ft_mapinsert(map, "pwgfodjsaighjfsdd", "1");
	ft_mapinsert(map, "pwsdagd", "1");
	ft_mapinsert(map, "dsagagpwd", "1");
	ft_mapinsert(map, "sagpdsgadfgwd", "1");
	ft_mapinsert(map, "13p321515wd523", "1");
	ft_mapinsert(map, "fafgkhjkdfpfafawd", "1");
	ft_mapinsert(map, "6562845pwdsgd", "1");
	ft_mapinsert(map, "pgafsdgwdg&&^%&# @!", "1");
	ft_mapinsert(map, "psdlgkakwd", "1");
	ft_mapinsert(map, "sdkO;,XLGKLSDKG'GLPpwd", "1");
	ft_mapinsert(map, "FKLHJLJHFL64236Qpwd", "1");
	ft_mapinsert(map, "dsagljafkgjpwgasdd", "1");
	ft_mapinsert(map, "pgdsawgasdgd", "1");
	ft_mapinsert(map, "35ya`$$Y^pwjdfgjd", "1");
	ft_mapinsert(map, "kjkfhpwd", "1");
	ft_mapinsert(map, "asdfjkgjakjkldks``~~~pwd", "1");
	ft_mapinsert(map, "~sdogk**&#*8782pwgdsgGSHSHSdGSSH", "1");
	ft_mapinsert(map, "pnjfhajfwd", "1");
	ft_mapinsert(map, "safahjlkjlpwd", "1");
	ft_mapinsert(map, "p+++wd", "1");
	ft_mapinsert(map, "pfljhkwkfd", "1");
	ft_mapinsert(map, "---------------pwd", "1");
	ft_mapinsert(map, "pwd224462184*=**/", "1");
	ft_mapinsert(map, "9**9-96-65+pwd", "1");
	ft_mapinsert(map, "fkjhgkpwd", "1");
	ft_mapinsert(map, "pfsadgaGDadfhdfahSGSDGSGGGGSDafhdhdfhgfshGKSHGJJSGJHSHGHSDHHJ SD HJHFG H344H48`&Y^&Y U(99358738U&*#^&wd", "1");
	ft_mapinsert(map, "GDS`KHfdahGSK", "1");
	ft_mapinsert(map, "pwgfoafdh43djsaighjfsdd", "1");
	ft_mapinsert(map, "pwsdag54315d", "1");
	ft_mapinsert(map, "dsa143566163154yhtegagpwd", "1");
	ft_mapinsert(map, "sagpd1346sgadfgwd", "1");
	ft_mapinsert(map, "13p32151164315wd523", "1");
	ft_mapinsert(map, "fafgkhjkdfpf61423afawd", "1");
	ft_mapinsert(map, "6562845pw3416dsgd", "1");
	ft_mapinsert(map, "pgafs4316169gfjsnhogjaedgwdg&&^%&# @!", "1");
	ft_mapinsert(map, "psdlghagsrkakwd", "1");
	ft_mapinsert(map, "sdkO;,XLG£yKLSD`66644$%$YY$#KG'GLPpwd", "1");
	ft_mapinsert(map, "FKLHJLJHFLqaghrg64236Qpwd", "1");
	ft_mapinsert(map, "dsagljafkgjp$T4twwgasdd", "1");
	ft_mapinsert(map, "pgdsawSHGDgasdgd", "1");
	ft_mapinsert(map, "35ya`$$Y^pwjdfgjd", "1");
	ft_mapinsert(map, "kjkfhpwHSFGDHSDd", "5");
	ft_mapinsert(map, "asdfjkgjakjkldSHFDHBGFSHDAATT`SDGVSks``~~~pwd", "1");
	ft_mapinsert(map, "~sdogk**&#*8782pwgdsg`GGSHSHSdGSSH", "1");
	ft_mapinsert(map, "pnjfhB`DKJJ`DKajfwd", "1");
	ft_mapinsert(map, "safahjlk25643(O)$jlpwd", "1");
	ft_mapinsert(map, "p+dsglkll++wd", "1");
	ft_mapinsert(map, "pfljhkwkdksjflafd", "1");
	ft_mapinsert(map, "-------dsagljafkgjp$T4twwgasddF--------pwd", "1");
	ft_mapinsert(map, "pg`f`dvwd224462184*=**/", "1");
	ft_mapinsert(map, "9**9-9fSDGHFDJHD6-65+pwd", "1");
	ft_mapinsert(map, "fkjhgkpdsagllwd", "1");
	ft_mapinsert(map, "faffghgkhjkdfpfafawd", "1");
	ft_mapinsert(map, "656284hgsf5pwdsgd", "1");
	ft_mapinsert(map, "pgafsdgwahdg&&^%&# @!", "1");
	ft_mapinsert(map, "psdlgkakwhad", "1");
	ft_mapinsert(map, "sdkO;,XLGahfKLSDKG'GLPpwd", "1");
	ft_mapinsert(map, "FKLHJLJHFL6fadhgfj;4236Qpwd", "1");
	ft_mapinsert(map, "dsagljafkgj;ghkpwgasdd", "1");
	ft_mapinsert(map, "pgdsawgas346dgd", "1");
	ft_mapinsert(map, "35ya`$$Y^p6q43gsrwjdfgjd", "1");
	ft_mapinsert(map, "kjkfsgfhpwd", "1");
	ft_mapinsert(map, "asdfjkahfdhgjakjkldks``~~~pwd", "1");
	ft_mapinsert(map, "~sdogk**&#*ahfdjh55a4+8782pwgdsgGSHSHSdGSSH", "1");
	ft_mapinsert(map, "pnjfhajf5wd", "1");
	ft_mapinsert(map, "safahjlk2jlpwd", "1");
	ft_mapinsert(map, "p+++w3d", "1");
	ft_mapinsert(map, "pfljh25kwkfd", "1");
	ft_mapinsert(map, "------2---------pwd", "1");
	ft_mapinsert(map, "pwd223224462184*=**/", "1");
	ft_mapinsert(map, "9**9-2922116-65+pwd", "1");
	ft_mapinsert(map, "fkjhgk2pwd", "1");
	ft_mapinsert(map, "pfsadgaG2DadfhdfahSGSDGSGGGGSDafhdhdfhgfshGKSHGJJSGJHSHGHSDHHJ SD HJHFG H344H48`&Y^&Y U(99358738U&*#^&wd", "1");
	ft_mapinsert(map, "GDS`KgHfdahGSK", "1");
	ft_mapinsert(map, "pwdfgfgoafdh43djsaighjfsdd", "1");
	ft_mapinsert(map, "pwsdag5gg4315d", "1");
	ft_mapinsert(map, "dsa14356ggggg6163154yhtegagpwd", "1");
	ft_mapinsert(map, "sagpd1346sggadfgwd", "1");
	ft_mapinsert(map, "13gcvp321511643g15wd523", "1");
	ft_mapinsert(map, "fafgkhjkdfpf61423afawd", "1");
	ft_mapinsert(map, "65628v45pw3416dsgd", "1");
	ft_mapinsert(map, "pgafs4vv316169gfjsnhogjaedgwdg&&^%&# @!", "1");
	ft_mapinsert(map, "psdlghagvgsrkakwd", "1");
	ft_mapinsert(map, "sdkO;,XLG£vgvyKLSD`66644$%$YY$#KG'GLPpwd", "1");
	ft_mapinsert(map, "FKLHJLJHFLqagvhrg64236Qpwd", "1");
	ft_mapinsert(map, "dsagljafkgjp$Tvg4twwgasdd", "1");
	ft_mapinsert(map, "pgdsawSHGDgasdgdv", "1");
	ft_mapinsert(map, "3vhvv5ya`$$Y^pwjdfgjd", "1");
	ft_mapinsert(map, "kjkfhvhpwHSFGDHSDd", "5");
	ft_mapinsert(map, "asdfjkgvjakjkldSHFDHBGFSHDAATT`SDGVSks``~~~pwd", "1");
	ft_mapinsert(map, "~sdogk**vv&#*8782pwgdsg`GGSHSHSdGSSH", "1");
	ft_mapinsert(map, "pnjfhB`DKJhJ`DKajfwd", "1");
	ft_mapinsert(map, "safahjlk256v43(O)$jlpwd", "1");
	ft_mapinsert(map, "p+dsglkll++whd", "1");
	ft_mapinsert(map, "pvhfljhkwkdksjflafd", "1");
	ft_mapinsert(map, "---vh----dsagljafkgjp$T4twwgasddF--------pwd", "1");
	ft_mapinsert(map, "pg`f`vdhhvwd224462184*=**/", "1");
	ft_mapinsert(map, "9**9-9hfSvDGHFDJHD6-65+pwd", "1");
	ft_mapinsert(map, "fkjhgkpdsavvgllwd", "1");
	ft_mapinsert(map, "pw25gsagSDGADHAHd", "1");
	ft_mapinsert(map, "pwsafg&*^&&d", "1");
	ft_mapinsert(map, "asap#%#H3QJwd", "1");
	ft_mapinsert(map, "padfwFDHSHDFAd", "1");
	ft_mapinsert(map, "AFHadfGpwd", "1");
	ft_mapinsert(map, "ASHGdst43tFHDApwd", "1");
	ft_mapinsert(map, "pfsadgaGD436tSGSDGSGGGGSDafhdhdfhgfshGKSHGJJSGJHSHGHSDHHJ SD HJHFG H344H48`&Y^&Y U(99358738U&*#^&wd", "1");
	ft_mapinsert(map, "GDS`K43HGSK", "1");
	ft_mapinsert(map, "pwgfod25252jsaighjfsdd", "1");
	ft_mapinsert(map, "pwsdag252d", "1");
	ft_mapinsert(map, "d253sagagpwd", "1");
	ft_mapinsert(map, "sagp235dsgadfgwd", "1");
	ft_mapinsert(map, "13p3215215wd523", "1");
	ft_mapinsert(map, "fafgkhjkdfp222fafawd", "1");
	ft_mapinsert(map, "65622845p2wdsgd", "1");
	ft_mapinsert(map, "pgafs2dgwd22g&&^%&# @!", "1");
	ft_mapinsert(map, "psdlgk2akwd", "1");
	ft_mapinsert(map, "sdkO;,XL2222GKLSDKG'GLPpwd", "1");
	ft_mapinsert(map, "FKLHJLJ22HFL64236Qpwd", "1");
	ft_mapinsert(map, "dsadasggljafkgjpwgasdd", "1");
	ft_mapinsert(map, "pgdsawasgdgasdgd", "1");
	ft_mapinsert(map, "35ya`$$asdgY^pwjdfgjd", "1");
	ft_mapinsert(map, "kjkfhasdgpwd", "1");
	ft_mapinsert(map, "asdfjkgdddjakjkldks``~~~pwd", "1");
	ft_mapinsert(map, "~sdogk**&dd#*8782pwgdsgGSHSHSdGSSH", "1");
	ft_mapinsert(map, "pnjddfhajfwd", "1");
	ft_mapinsert(map, "safadddhjlkjlpwd", "1");
	ft_mapinsert(map, "p++ddd+wd", "1");
	ft_mapinsert(map, "pfljhdsfkwkfd", "1");
	ft_mapinsert(map, "-------daf--------pwd", "1");
	ft_mapinsert(map, "pwd2af24462184*=**/", "1");
	ft_mapinsert(map, "9**9-saf96-65+pwd", "1");
	ft_mapinsert(map, "fkdafjhgkpwd", "1");
	ft_mapinsert(map, "pfsadsgaGDadfhdfahSGSDGSGGGGSDafhdhdfhgfshGKSHGJJSGJHSHGHSDHHJ SD HJHFG H344H48`&Y^&Y U(99358738U&*#^&wd", "1");
	ft_mapinsert(map, "GDS`KHsfdahGSK", "1");
	ft_mapinsert(map, "pwgfoafsdh4s3djsaighjfsdd", "1");
	ft_mapinsert(map, "pwsdag54s315d", "1");
	ft_mapinsert(map, "dsa14fsa3566s163154yhtegagpwd", "1");
	ft_mapinsert(map, "sagpsdasf1346ssgadfgwd", "1");
	ft_mapinsert(map, "13sap3215sfa1164315wd523", "1");
	ft_mapinsert(map, "fafgksshjkdfpf61423afawd", "1");
	ft_mapinsert(map, "6562845gadssspw3416dsgd", "1");
	ft_mapinsert(map, "pgafs4316gasdfg169gfjsnhogjaedgwdg&&^%&# @!", "1");
	ft_mapinsert(map, "psdlghagagsdsrkakwd", "1");
	ft_mapinsert(map, "sdkO;asf,XLG£yKLSD`66644$%$YY$#KG'GLPpwd", "1");
	ft_mapinsert(map, "FKLHasfJLJHFLqaghrg64236Qpwd", "1");
	ft_mapinsert(map, "dsagljsafkgjp$T4twwgasdd", "1");
	ft_mapinsert(map, "pgdsawSssHGDgasdgd", "1");
	ft_mapinsert(map, "35ya`$$Y^spwjdfgjd", "1");
	ft_mapinsert(map, "kjkfhpwHSFsGDHSDd", "5");
	ft_mapinsert(map, "asdfjkgjakjskldSHFDHBGFSHDAATT`SDGVSks``~~~pwd", "1");
	ft_mapinsert(map, "~sdogk**&#*8s782pwgdsg`GGSHSHSdGSSH", "1");
	ft_mapinsert(map, "pnjfhB`DKJJ`DsKajfwd", "1");
	ft_mapinsert(map, "safahjlk25fa643(sO)$jlpwd", "1");
	ft_mapinsert(map, "p+ds53glkllfa++wd", "1");
	ft_mapinsert(map, "pfljh634634kwkdksjflafd", "1");
	ft_mapinsert(map, "---36----dsagljafkgjp$T4twwgasddF--------pwd", "1");
	ft_mapinsert(map, "pg`f345763`dvwd224462184*=**/", "1");
	ft_mapinsert(map, "9**9-9fSDreysGHFDJHD6-65+pwd", "1");
	ft_mapinsert(map, "fkjhgkpdsag6735llwd", "1");
	ft_mapinsert(map, "faffghgsfgkhjkdfpfafawd", "1");
	ft_mapinsert(map, "6562f84hgsf5pwdsgd", "1");
	ft_mapinsert(map, "pgafsfdgwffahdg&&^%&# @!", "1");
	ft_mapinsert(map, "psdlgkfakwhad", "1");
	ft_mapinsert(map, "sdkOff;,XffLGahfKLSDKG'GLPpwd", "1");
	ft_mapinsert(map, "FKLHJfLJHFL6fadhgfj;4236Qpwd", "1");
	ft_mapinsert(map, "dsagljfafkgj;ghkpwgasdd", "1");
	ft_mapinsert(map, "pgdsawgfas346dgd", "1");
	ft_mapinsert(map, "35ya`$$Yff^p6q43gsrwjdfgjd", "1");
	ft_mapinsert(map, "kjkfffsgfhpwd", "1");
	ft_mapinsert(map, "asdfjfkahfdhgjakjkldks``~~~pwd", "1");
	ft_mapinsert(map, "~sdogkf**&#*ahfdjh55a4+8782pwgdsgGSHSHSdGSSH", "1");
	ft_mapinsert(map, "pnjfhajfffff5wd", "1");
	ft_mapinsert(map, "saf536ahjlk2jlpwd", "1");
	ft_mapinsert(map, "p+3426++346w3d", "1");
	ft_mapinsert(map, "pstg^fljh25kwkfd", "1");
	ft_mapinsert(map, "-----#-2---------pwd", "1");
	ft_mapinsert(map, "pwd22#3224462184*=**/", "1");
	ft_mapinsert(map, "9**9-142922116-65+pwd", "1");
	ft_mapinsert(map, "fkjhgk412pwd", "1");
	ft_mapinsert(map, "pfsadg124aG2DadfhdfahSGSDGSGGGGSDafhdhdfhgfshGKSHGJJSGJHSHGHSDHHJ SD HJHFG H344H48`&Y^&Y U(99358738U&*#^&wd", "1");
	ft_mapinsert(map, "GDS`KgHf142dahGSK", "1");
	ft_mapinsert(map, "pwdfgfgoa124fdh43djsaighjfsdd", "1");
	ft_mapinsert(map, "pwsdag1245gg4315d", "1");
	ft_mapinsert(map, "dsa14356421ggggg6163154yhtegagpwd", "1");
	ft_mapinsert(map, "sag214pd1346sggadfgwd", "1");
	ft_mapinsert(map, "13gcv241p321511643g15wd523", "1");
	ft_mapinsert(map, "fafgkhjkdfpf61423afawd", "1");
	ft_mapinsert(map, "65628v4214esdf`5pw3416dsgd", "1");
	ft_mapinsert(map, "pgafs4vv3161623q9gfjsnhogjaedgwdg&&^%&# @!", "1");
	ft_mapinsert(map, "psdlghfdsagvgsrkakwd", "1");
	ft_mapinsert(map, "sdkO;,XLdfsG£vgvyKLSD`66644$%$YY$#KG'GLPpwd", "1");
	ft_mapinsert(map, "FKLHdJLddJHFLqagvhrg64236Qpwd", "1");
	ft_mapinsert(map, "dsaglsjafkgjp$Tvg4twwgasdd", "1");
	ft_mapinsert(map, "pgddddsaddwSHGDgasdgdv", "1");
	ft_mapinsert(map, "3vhvvd5ya`$d$Y^pwjdfgjd", "1");
	ft_mapinsert(map, "kjkfhvdhpwdHSFGDHSDd", "5");
	ft_mapinsert(map, "asdfjksgdvdjakjkldSHFDHBGFSHDAATT`SDGVSks``~~~pwd", "1");
	ft_mapinsert(map, "~sdogsk**dvv&dd#*8782pwgdsg`GGSHSHSdGSSH", "1");
	ft_mapinsert(map, "pnjfhBs`DKJhJ`DKajfwd", "1");
	ft_mapinsert(map, "safahjlsk256v43(O)$jlpwd", "1");
	ft_mapinsert(map, "p+dsglklssl++whd", "1");
	ft_mapinsert(map, "pvhfljhkwksdksjflafd", "1");
	ft_mapinsert(map, "---vh----dssagljafkgjp$T4twwgasddF--------pwd", "1");
	ft_mapinsert(map, "pg`f`vdhhvwds224462184*=**/", "1");
	ft_mapinsert(map, "9**9-9hfSvDGHssFDJHD6-65+pwd", "1");
	ft_mapinsert(map, "fkjhgkpdsavvglslwd", "1");
	ft_putmap(map);

	ft_mapdel(&map);
}

// int main()
// {
// 	t_map		*map;

// 	map = ft_mapnew(NULL);
// 	ft_mapinsert(map, "9**9-9hfSvDGHFDJHD6-65+pwd", "1");
// 	ft_mapinsert(map, "fkjhgkpdsavvgllwd", "1");
// 	ft_mapinsert(map, "---vh----dsagljafkgjp$T4twwgasddF--------pwd", "1");
// 	ft_mapinsert(map, "pg`f`vdhhvwd224462184*=**/", "1");
// 	ft_putmap(map);
// 	ft_mapdel(&map);
// }